/*/
File: QS_data_actions.sqf
Author:

	Quiksilver
	
Last modified:

	27/05/2019 A3 1.92 by Quiksilver
	
Description:

	Actions Text
___________________________________________/*/

[
	'Sit',
	'Stand',
	'Escort',
	'Load',
	'Load cargo',
	'Unload',
	'Unload cargo',
	'Question civilian',
	'Drag',
	'Carry',
	'Command Follow',
	'Command Recruit',
	'Command Dismiss',
	'Command Surrender',
	'Release',
	'Respawn vehicle',
	'Open cargo doors',
	'Close cargo doors',
	'Service vehicle',
	'Service',
	'Clear vehicle inventory',
	'Unflip',
	'Revive',
	(localize 'STR_A3_Arsenal'),
	'Beacons On',
	'Beacons Off',
	'Tow',
	'Rescue',
	'Secure',
	'Turret safety',
	'Collect ear',
	'Collect gold tooth',
	'Turn on live feed',
	'Turn off live feed',
	'Activate air defense',
	'Transport Leaderboard (Enable)',
	'Transport Leaderboard (Disable)',
	'Vote For Nighttime!',
	'Vote Against Nighttime!',
	'Unlock turret (Left)',
	'Unlock turret (Right)',
	'Lock turret (Left)',
	'Lock turret (Right)',
	'Cancel turret actions',
	'Join group',
	'FOB Status',
	'Activate FOB',
	'Enable FOB Respawn',
	'Cancel',
	'Unpack fortification',
	'Pack fortification',
	'Edit Inventory',
	'Pick up intel',
	'Drop intel',
	'Upload intel',
	'Activate device',
	'About Us',
	'Push vehicle',
	(localize 'STR_A3_BIS_fnc_initIntelObject_take'),
	'Take Intel',
	'Inflate boat',
	'Suspend side missions',
	'Resume side missions',
	'Suspend primary missions',
	'Resume primary missions',	
	'Cycle primary mission',
	'0 - Close Menu',
	'1 - (Target) Delete',
	'2 - Spectate',			
	'3 - Invincibility',
	'4 - Show Pilots',
	'5 - (Target) Repair',
	'6 - (Target) Pardon',
	'7 - (Target) Punish',
	'8 - No function assigned',
	'9 - No function assigned',
	'10 - (Target) Revive',
	'11 - Map Teleport',
	'12 - (Clean) Base',
	'13 - (Clean) Island',
	'14 - Splendid Cam',
	'15 - Dev Terminal',
	'Fastrope',
	'Fastrope AI units',
	'Detach fastrope',
	'Enable fastrope',
	'Disable fastrope',
	'   ',
	'Pick up',
	'Download Locations',
	'Get Intel',
	'Treat at Medical Station',
	'Activate vehicle',
	'Weapons safe on base',
	'Spawn plane',
	'Confirm target',
	'Report target',
	'Raise plow',
	'Lower plow',
	'Examine',
	(localize 'STR_A3_action_useCatapult'),
	'Initiate Launch Sequence',
	'Launch',
	'Stabilise',
	'Inspect',
	'Self destruct',
	'Deploy camo net',
	'Remove camo net',
	'Mount slat armor',
	'Remove slat armor',
	'Retract Cargo Ropes',
	'Extend Cargo Ropes',
	'Shorten Cargo Ropes',
	'Release Cargo',
	'Deploy Cargo Ropes',
	'Attach To Cargo Ropes',
	'Drop Cargo Ropes',
	'Pickup Cargo Ropes',
	(if (isLocalized 'STR_A3_action_Recover_Boat') then {localize 'STR_A3_action_Recover_Boat'} else {'Recover boat'}),
	'Role Selection',
	'Set Cruise Control',
	'Take controls'
]